replicaCount: 1
image: okteto.dev/vote

config:
  kafkaHost: "kafka"
  kafkaPort: "9092"
  kafkaTopic: "votes"

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
