apiVersion: v1
kind: ConfigMap
metadata:
  name: vote-config
  labels:
    app: vote
data:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "{{ .Values.config.kafkaHost }}:{{ .Values.config.kafkaPort }}"
  SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: "org.apache.kafka.common.serialization.StringSerializer"
  SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: "org.apache.kafka.common.serialization.StringSerializer"
  KAFKA_TOPIC: "{{ .Values.config.kafkaTopic }}"
