replicaCount: 1
image: okteto.dev/worker

config:
  kafkaHost: "kafka"
  kafkaPort: "9092"
  kafkaTopic: "votes"
  dbHost: "postgresql"
  dbPort: "5432"
  dbName: "votes"
  dbUser: "okteto"

resources:
  requests:
    cpu: "100m"
    memory: "64Mi"
  limits:
    cpu: "500m"
    memory: "128Mi"
