apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: worker
  name: worker
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: {{ .Values.image }}
        name: worker
        args:
        - "--brokerList={{ .Values.config.kafkaHost }}:{{ .Values.config.kafkaPort }}"
        - "--topic={{ .Values.config.kafkaTopic }}"
        envFrom:
        - configMapRef:
            name: worker-config
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
